directories:
  output: release-temp
  buildResources: build
appId: com.financaspessoais.app
productName: Finanças Pessoais
files:
  - filter:
      - dist/**/*
      - build/icon.ico
      - electron/**/*
      - src/backend/**/*
      - package.json
extraResources:
  - from: src/backend/db.producao.sqlite
    to: db.sqlite
asarUnpack:
  - node_modules/sqlite3/**/*
win:
  icon: build/icon.ico
  target: nsis
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
electronVersion: 39.8.10
